### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by bethanyhaubert** [bethanyhaubert/02-29-pair-project#1]

**Comment by bethanyhaubert** [comment]
Databases:

Movies
- title
- director
- actors/actresses
- image
- critic rating

Users
- name
- email
- password

Bechdel test results
- movie_id
- user_id
- q1
- q2
- q3

**Comment by halfghaninne** [comment]
What type of data is the actors/actresses column of your movies database?

**Comment by bethanyhaubert** [comment]
just a string. it's not an important piece of info for our site.

**Comment by halfghaninne** [comment]
Just wondering. That's the only piece that raised any questions for me :+1:
